### ISSUE TITLE
init fails to detect Thumb function that starts immediately after two bytes that look like the first half of a Thumb bl instruction, but aren't

### ISSUE THREAD

**Issue by LagoLunatic** [AetiasHax/ds-decomp#12]
Version: 0.2.3
Affects: Akumajou Dracula: Gallery of Labyrinth (ACBJ00 and ACBJ01) (does not affect ACBE00 or ACBP00)

```
[2024-11-23T23:08:48Z INFO  ds_rom::rom::rom] Loading ROM from orig/ACBJ00/config.yaml
[2024-11-23T23:08:48Z INFO  ds_decomp::analysis::functions] Function at 020a36bc was adjusted to include pre-code constant pool at 020a36a8
[2024-11-23T23:08:48Z ERROR ds_decomp::analysis::data] Function call from 0x020aff44 in ARM9 main to 0x02000796 leads to no function
Error: Function call leads nowhere, see above
```

02000796 is where the CpuSet (swi 0xB) secure area function is at in this game:
![image](https://github.com/user-attachments/assets/c52297f2-0b69-4e3f-a426-7a15eafbd3b2)

The two bytes before the function are `F600`, which unarm interprets to be the first half of a bl instruction, and therefore decides to read ahead the next two bytes and combine them into this bl instruction:
https://github.com/AetiasHax/unarm/blob/5712d8890b449fa73ac3f60d1882503d5f0c78ef/disasm/src/parse.rs#L81-L86

because unarm's parser jumps ahead from 02000794 to 02000798, `find_secure_area_functions` never sees the function that starts at 02000796:
https://github.com/AetiasHax/ds-decomp/blob/6e582779df7ff8ebe113c3a0f7db1abcb17ea820/src/analysis/functions.rs#L507-L509

**Comment by AetiasHax** [comment]
Fixed as of v0.3.0! https://github.com/AetiasHax/ds-decomp/commit/01bfc35988c89289bc84091d94d029616b711abd
