### ISSUE TITLE
Error on function call to address without code on dsd init

### ISSUE THREAD

**Issue by Yackerw** [AetiasHax/ds-decomp#17]
Attempting to run dsd init on Dragon Quest IX spits out the following error:

[2024-12-09T20:47:56Z ERROR ds_decomp::analysis::data] Function call from 0x02075648 in ARM9 main to 0x02000140 leads to no function
Error: Function call leads nowhere, see above

This is, in fact, expected and normal behavior for the game, but dsd insists it's wrong. Ghidra reports 0x02000140 as a valid function that sets an interrupt and then returns.

**Comment by AetiasHax** [comment]
What does the function look like? Functions in 0x02000000 to 0x02000800 are indeed interrupt functions, but if we're missing one then it needs to be added to `secure_area.rs` so dsd can detect it.

**Comment by Yackerw** [comment]
It's literally 2 thumb opcodes;
svc 0x11
bx lr

I'm not intimately familiar with ARM enough to know what exactly svc is, but ghidra decompiles it to "software_interrupt(0x11);", which I'm taking to mean as triggering an interrupt, rather than handling one.

**Comment by LagoLunatic** [comment]
If the byte right before the function starts with the hex digit `F`, then it might be the same bug as #12.

**Comment by Yackerw** [comment]
Oh, yes it does! It's F5. That explains it.

**Comment by AetiasHax** [comment]
Should be fixed as of v0.3.0!
