### ISSUE TITLE
Panic on `dsd init` - attempt to subtract with overflow

### ISSUE THREAD

**Issue by Eebit** [AetiasHax/ds-decomp#2]
While running `dsd init` on Fire Emblem: Shadow Dragon (US), I encountered a panic due to a subtraction overflow.

OS: Windows
ds-decomp version: 0.1.0 (built from main with local ds-rom)
ds-rom version: 0.2.2

<details>
<summary>Logs:</summary>

```
$ ./target/debug/dsd.exe init --extract-path <snip>/fe11/dis/ --output-path <snip>/fe11/dsd_out --dry true
[2024-09-10T00:46:27Z INFO  ds_rom::rom::rom] Loading ROM from path <snip>/fe11/dis/
[2024-09-10T00:46:27Z INFO  ds_rom::rom::rom] Loading ROM assets
[2024-09-10T00:46:27Z WARN  dsd::config::module] Expected .text to end (0x20aa37c) where .init starts (0x20c4cdc)
thread 'main' panicked at src\analysis\functions.rs:386:25:
attempt to subtract with overflow
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:181
   3: dsd::analysis::functions::impl$0::iter_pool_constants::closure$0
             at .\src\analysis\functions.rs:386
   4: core::ops::function::impls::impl$4::call_once<tuple$<ref$<u32> >,dsd::analysis::functions::impl$0::iter_pool_constants::closure_env$0>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:305
   5: enum2$<core::option::Option<ref$<u32> > >::map
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\option.rs:1110
   6: core::iter::adapters::map::impl$2::next<dsd::analysis::functions::PoolConstant,alloc::collections::btree::set::Iter<u32>,dsd::analysis::functions::impl$0::iter_pool_constants::closure_env$0>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\iter\adapters\map.rs:108
   7: dsd::analysis::data::find_local_data_from_pools
             at .\src\analysis\data.rs:21
   8: dsd::config::module::Module::find_data_from_pools
             at .\src\config\module.rs:403
   9: dsd::config::module::Module::analyze_arm9
             at .\src\config\module.rs:76
  10: dsd::cmd::init::Init::run
             at .\src\cmd\init.rs:50
  11: enum2$<dsd::Command>::run
             at .\src\main.rs:32
  12: dsd::main
             at .\src\main.rs:42
  13: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

I added a bit of additional logging to help with troubleshooting:

```
$ ./target/debug/dsd.exe init --extract-path <snip>/fe11/dis/ --output-path <snip>/fe11/dsd_out --dry true
[2024-09-10T00:56:56Z INFO  ds_rom::rom::rom] Loading ROM from path <snip>/fe11/dis/
[2024-09-10T00:56:56Z INFO  ds_rom::rom::rom] Loading ROM assets
[2024-09-10T00:56:56Z WARN  dsd::config::module] Expected .text to end (0x20aa37c) where .init starts (0x20c4cdc)
[2024-09-10T00:56:56Z ERROR dsd::analysis::functions] Name: _0200bc0c: Address 0x200bbe0 is less than start_address 0x200bc0c
[2024-09-10T00:56:56Z ERROR dsd::analysis::functions] Name: _0200bc0c: Address 0x200bbe4 is less than start_address 0x200bc0c
[2024-09-10T00:56:56Z ERROR dsd::analysis::functions] Name: _0200bc0c: Address 0x200bbe8 is less than start_address 0x200bc0c
```

Based on the output of the function in question from [`ndsdisasm`](https://github.com/PikalaxALT/ndsdisasm), it's coming from a significantly large function (~1300 lines of assembly!) which features a backwards branch to before a pool, which seems to be used as a heuristic for determining the end of the function in `dsd`:

https://github.com/AetiasHax/ds-decomp/blob/4e1130def15ae7d1bb1f469b7cb612edae28f744/src/analysis/functions.rs#L628-L635

For reference, the affected function starts at `0x0200AB0C` in FE: Shadow Dragon. If it's useful for me to upload the byte string somewhere, let me know and I'll do so. :)

**Comment by AetiasHax** [comment]
If I understand correctly, the function in question has a backwards branch right before one of its constant pools. Is that pool then skipped over by a different branch instruction somewhere?

I had assumed that pools were always skipped by the preceding branch instruction, but it seems to me that this function is a rare edge case where this doesn't happen?

**Comment by Eebit** [comment]
Yeah, it seems like it's a very rare / very particular case (as far as I can tell, the only such case in this game). The pool does get skipped over in a different part of the function.

Here is a gist with the function disassembly from `ndsdisasm`. The offending part of the function is L1095-L1098: https://gist.github.com/Eebit/41a79718ada44675e67c56e35d1f1fdb

**Comment by Yanis42** [comment]
this issue is also present on Spirit Tracks (JP), it might not be as rare as it seems? maybe Phantom Hourglass was just lucky? 🤔

**Comment by AetiasHax** [comment]
Judging by https://github.com/Eebit/fe11-us, I guess this is fixed? dsd handles a lot more cases with constant pools and branches now than before.

**Comment by Eebit** [comment]
Yes, thank you! I had been using a locally-modified `dsd` previously to bypass the issue, but I just re-tested `dsd init` from scratch on FE11 and it no longer panics on this case. Thanks a lot for the fix!
